"""
Triodion_Data - Auto-extracted from PDFs
Generated by database/extract_services.py
Data loaded from triodion_data.json
"""

import json
import os

_dir = os.path.dirname(os.path.abspath(__file__))
_json_path = os.path.join(_dir, 'database', 'triodion_data.json')

with open(_json_path, "r", encoding="utf-8") as _f:
    triodion_data = json.load(_f)
